apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-promtail-config
  namespace: nginx
data:
  promtail.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.monitoring.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: nginx-sidecar
        static_configs:
          - targets:
              - localhost
            labels:
              job: nginx-sidecar
              __path__: /var/log/nginx-logs/access.log